import Head from 'next/head'
import IntroPart from './IntroPart'
import About from './About'
import MyProjects from './MyProjects'
import Contact from './Contact'
import NavBar from '@/components/NavBar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio de Marvin Rodrigues Novo Développeur Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <IntroPart />
        <About />
        <MyProjects />
        <Contact />
      </main>
    </>
  )
}
